### ISSUE TITLE
Weird Issue!

### ISSUE THREAD

**Issue by felixsanz** [arve0/markdown-it-implicit-figures#11]
Probably a special use case, but check this example:

https://jsfiddle.net/jzyag4pv/2/

As you can see, that ``File > Examples > Firmata > StandardFirmata`` string is breaking something

**Comment by arve0** [comment]
Thanks for reporting 👍 Suspect that this have something to do with #10

**Comment by arve0** [comment]
Confirmed, [works](https://jsfiddle.net/2g35ftej/) with [v0.2.3](https://github.com/arve0/markdown-it-implicit-figures/blob/f6fdacd0621ba6dc2d238c7908fa7a9d797c90f7/index.js).

**Comment by arve0** [comment]
Fixed in v0.3.1.

https://jsfiddle.net/jzyag4pv/3/ (used wzrd.in to load latest plugin, "External resources")

**Comment by felixsanz** [comment]
I tried wzrd.in for 30 minutes to end up giving up, it was saying that `markdownItImplicitFigures` is undefined xD

Thanks for fixin!
