### ISSUE TITLE
Plugin should run before replacements/linkify stages

### ISSUE THREAD

**Issue by cocoademon** [arve0/markdown-it-implicit-figures#16]
URLs in figure captions aren't detected by linkify, as this plugin gets added at the end of the chain.

It would be better if the line to add the plugin was:

```javascript
md.core.ruler.after('inline', 'implicit_figures', implicitFigures);
```

This way, linkify, smartquotes, etc can still run on the figure caption.

**Comment by arve0** [comment]
Thanks for reporting. Fixed in `v0.4.0`.
