### ISSUE TITLE
Pandoc uses the [alt text] for the caption, perhaps this should as well?

### ISSUE THREAD

**Issue by mshick** [arve0/markdown-it-implicit-figures#2]
Using the alt text, or maybe the `title` as figcaption content makes some sense to me. Perhaps would be a good default with config to turn it off?

**Comment by mshick** [comment]
FYI, if desired I can open a PR for this. Should be fairly straightforward.

**Comment by arve0** [comment]
I prefer the alt `![text](img.png)` notation, but not sure what pandoc uses? I guess that this can be easily configured, if someone else prefers `![](img.png "text")`.

**Comment by arve0** [comment]
PR is always welcome :+1:

**Comment by mshick** [comment]
I see an easy way to do this by overriding the default image renderer -- similar to how this module was working to generate figures before. I'm worried that the easy way is not the "right" way though. 

Seems that if a tag is being added it should be presented as a token rather than raw output. I've worked through most of the logic, but can't seem to find any place where the `Token` class is available in the `core.ruler` extension that we're now using to loop through the tokens. Perhaps you know? Am I missing something? Is there some preferred way of accessing it?

**Comment by mshick** [comment]
I found it! Please check out my PR.

**Comment by arve0** [comment]
Released in v0.2.0 just now. Thanks for the help!
