### ISSUE TITLE
Add wrapping div around img

### ISSUE THREAD

**Issue by lukasoppermann** [arve0/markdown-it-implicit-figures#22]
Hey,
nice package. I have one small thing I think could improve it: adding a wrapping div around the img tag. This would be nice because it makes positioning of the caption and image easier.

**Comment by ToniWonKanobi** [comment]
Does this make sense semantically? (Who wraps an `<img>` in a generic container like `<div>`?)

**Comment by lukasoppermann** [comment]
A `div` does not have any semantic meaning, that's why it is an ideal wrapper. People have always wrapped images in divs, now of course figure replaces this need for a div. But if you add a caption and you want to align caption and image inside the figure, a div can be quite helpful, as images are not as versatile as divs. Also if for some resizing techniques a div wrapper is very handy, the figure would not work for that due to the caption inside.

**Comment by ToniWonKanobi** [comment]
You said it: a <div> has no semantic meaning—that's why replacing <figure> with a generic container like <div> doesn't make any sense. That would be the definition of regression 😂

**Comment by lukasoppermann** [comment]
Okay, I think this is a misunderstanding, what I would think would be good is:

```html
<figure>
<div>
<img />
</div>
<figcaption>…</figcaption>
</figure>
```

**Comment by ToniWonKanobi** [comment]
Oh. Well, that's still redundant, no? Why not just style the <figure> directly?

**Comment by lukasoppermann** [comment]
No, its not, as I explained above, styling the `figure` will include the `figcaption`. However, often one wants to style them separately for e.g. when setting a flexible size for the div, making the image scale to 100% (but with overflow:hidden on the div and a max-height to scale it only up to a point). The Caption however should have a fixed size.

**Comment by arve0** [comment]
Hi there :-)
I'm confident that custom rendering for `<img>` is outside the scope of this package. You can quite easily add a custom renderer yourself:

```js
md.renderer.rules.image = function (tokens, idx, opts, _, slf) {
  return '<div>' + slf.renderToken(tokens, idx, opts) + '</div>';
}
```

I'm not a CSS-ninja, but the style you describe also seems possible with something like `figure > img` and `figure > figcaption`, though it might be way easier if you wrap the `<img>` in a `<div>`.

**Edit**: `md.renderer.rules.image` not `md.renderer.rules.img`

**Comment by arve0** [comment]
You could read more about custom renderers here: https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer

**Comment by lukasoppermann** [comment]
Thank you for the alternative solution.
