### ISSUE TITLE
Automatically create anchor

### ISSUE THREAD

**Issue by adam-lynch** [arve0/markdown-it-implicit-figures#23]
I want all my figures to have a link to a full res image. Right now I'm doing this everywhere:

```markdown
[![alt](url)](highResUrl)
```

Would it make sense to add option(s) for this?

**Comment by arve0** [comment]
I believe that is outside the scope of this plugin, but you can easily create it yourself with markdown-it-for-inline: https://www.npmjs.com/package/markdown-it-for-inline

**Comment by adam-lynch** [comment]
OK cool but gotta say: 👎 it's not easy. The docs for that plugin are poor. The source and tests even don't show how to really use it. I successfully replaced the text (`:::figure url caption`) with what I want (HTML) but that's just outputted as text. So I guess I need to update & add tokens. Markdown-it-for-inline doesn't give you access to the token constructor (maybe it's not the right module to use if I want to add tokens? I don't know). I've looked a few plugins source and read some of the markdown-it dev docs but still not quite there. My experience with markdown-it up until now has been great, so quick and easy (E.g. need emoji? Just use this plugin), but to implement this small thing, there's a good bit of digging I need to do. Other markdown packages in the past I've used allow you to easily just return a HTML string to overwrite the rendering of something. The markdown-it docs could be better too I'd say; there isn't a list of tokens (I had to use the "debug" tab [here](https://markdown-it.github.io/) to help), it doesn't tell you where you can access the token constructor, etc.

`</rant>` 😁 

Thanks for this plugin though 😄

**Comment by arve0** [comment]
I feel your pain, but I'm sorry to say, you are on your own. You can't really expect others to do the work for you.

>  I've looked a few plugins source and read some of the markdown-it dev docs but still not quite there.

Have you read the code of this plugin? It's only 70 lines. It might shed some light to your frustrations. For example, creating tokens here: https://github.com/arve0/markdown-it-implicit-figures/blob/master/index.js#L50

Good luck :octocat:

**Comment by adam-lynch** [comment]
> You can't really expect others to do the work for you.

Ah it's not that really.

Thanks, yeah I did read through that and it helped a bit. I definitely have a better understanding now but still figuring it some issues with the output.

👍

**Comment by adam-lynch** [comment]
For anyone looking to anything like this in future. I ended up using https://github.com/markdown-it/markdown-it-container. It's pretty easy to work with (because you can just use arbitrary HTML). I ended up with something like this in my Markdown:

```markdown
:::figure as many different options you want
:::
```
