### ISSUE TITLE
Expansion of single-link paragraphs 

### ISSUE THREAD

**Issue by Crissov** [arve0/markdown-it-implicit-figures#32]
Would it be in scope of this plugin to turn paragraphs that consist of a single link into a preview using metadata from the linked URL?

This could mean using the title of the resource, a preview or logo image, an author, a description, generating an excerpt etc. This can be extracted either from standard HTML elements, e.g. `<title>`, or Facebook's [Open Graph](http://ogp.me/), e.g. `<meta property="og:title" content="foo" />` and [Twitter Card](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html), e.g. `<meta name="twitter:title" content="foo" />`, meta data.

**Comment by arve0** [comment]
Hi! Sounds like a great idea, but out of scope. Feel free to fork and use this plugin as a start.
