### ISSUE TITLE
option to keep alt text with figcaption

### ISSUE THREAD

**Issue by ItaiAxelrad** [arve0/markdown-it-implicit-figures#38]
Would it be possible to provide an option to keep the alt text when figcaption is set to true? Currently, it is removed.

**Comment by arve0** [comment]
You will get that behavior if you pin to the previous version, v0.9.0.

**Comment by tcurdt** [comment]
@arve0 and what will be the behaviour in the next release?
I was just to open an issue about this.

https://www.scottohara.me/blog/2019/01/21/how-do-you-figure.html#a-figcaption-is-not-a-substitute-for-alt-text

**Comment by arve0** [comment]
> what will be the behaviour in the next release?

Releases with major version 0 after 0.10 will not render alt when `figcaption == true`.

**Comment by tcurdt** [comment]
Given the above article, should I open an issue to make this configurable in the next release?

**Comment by arve0** [comment]
Sure, give it a try. I regard that option a minuscule issue, as "rendering alt" is the only difference between 0.9 and 0.10. Therefore I will not prioritize time for it.
