### ISSUE TITLE
Images with Alternate Text *and* a Title

### ISSUE THREAD

**Issue by ToniWonKanobi** [arve0/markdown-it-implicit-figures#6]
How does `markdown-it-implicit-figures` deal with situations in which the image syntax contains an alternate text attribute `alt` _and_ a title `title`?

Consider this Markdown:

``` md
![Alternate text](image_link "Title")
```

Will `markdown-it-implicit-figures` parse this with the correct `alt` and `title` attributes, like so? (`figcaption` to `true`)

``` html
<figure>
    <img src="image_link" alt="Alternate text" title="Title">
    <figcaption>Alternate text</figcaption>
</figure>
```

**Comment by arve0** [comment]
> Will markdown-it-implicit-figures parse this with the correct alt and title attributes, like so? 

Yes. https://jsfiddle.net/arve0/1kk1h6p3/1/
