### ISSUE TITLE
Reference-style Image Syntax

### ISSUE THREAD

**Issue by ToniWonKanobi** [arve0/markdown-it-implicit-figures#7]
How does `markdown-it-implicit-figures` deal with reference-style image syntax?

Consider the following Markdown:

``` md
![Alternate text][1]

[1]: image_link
```

Does the above Markdown get correctly parsed like this (`figcaption` set to `true`)

``` html
<figure>
    <img src="image_link" alt="Alternate text">
    <figcaption>Alternate text</figcaption>
</figure>
```

**Comment by arve0** [comment]
> Does the above Markdown get correctly parsed like this (figcaption set to true)

Yes. https://jsfiddle.net/arve0/1kk1h6p3/2/

**Comment by Crissov** [comment]
Maybe you should document that in the README.
