### ISSUE TITLE
Reference-Style Image/Link Attributes (Like MultiMarkdown 3+)

### ISSUE THREAD

**Issue by ToniWonKanobi** [arve0/markdown-it-implicit-figures#8]
How difficult would it be to get `markdown-it-implicit-figures`to parse image/link attributes like [MultiMarkdown](http://fletcher.github.io/MultiMarkdown-4/attributes.html) does? (You're already half-way there with this whole project :D)

Here's a screenshot of some example Markdown parsing:

[![MMD example](http://d.pr/i/1g8DC+)](http://d.pr/i/1g8DC)

Specifically, consider this Markdown:

``` md
![Alternate text][1]

[1]: image_link "Title" width=100px
```

parsing as I've suggested would lead to this result

``` html
<figure>
    <img src="image_link" alt="Alternate text" title="Title" width="100px">
    <figcaption>Alternate text</figcaption>
</figure>
```

---

For a stretch goal, how about allowing _any_ image/link reference with _any_ random attribute?

Consider this Markdown, with the more generic inline `style` attribute, with the `width` parameter and `value` declared:

``` md
![Alternate text][1]

[1]: image_link "Title" style="width: 100px;"
```

parse:

``` html
<figure>
    <img src="image_link" alt="Alternate text" title="Title" style="width: 100px;">
    <figcaption>Alternate text</figcaption>
</figure>
```

Or, even a `class` or `id` attribute in the Markdown:

``` md
![Alternate text][1]

[1]: image_link "Title" style="width: 100px;" class="small" id="pic"
```

parse:

``` html
<figure>
    <img src="image_link" alt="Alternate text" title="Title" style="width: 100px;" class="small" id="pic">
    <figcaption>Alternate text</figcaption>
</figure>
```

Is this too difficult to achieve?

**Comment by arve0** [comment]
You can use [attrs](https://github.com/arve0/markdown-it-attrs) or [decorate](https://github.com/rstacruz/markdown-it-decorate) for that. Then transform your markdown with a regex to the new syntax.

**Comment by ToniWonKanobi** [comment]
Your's is _so_ close to the MultiMarkdown 3 spec already though! :)

**Comment by arve0** [comment]
Well, I'm not trying to ape MultiMarkdown, I'm aping [pandoc](http://pandoc.org/). 

Though, it should be relative easy to implement, if you make an effort. I will accept PRs.

**Comment by ToniWonKanobi** [comment]
Something like this, but more generic maybe? https://github.com/tatsy/markdown-it-imsize/blob/master/dist/markdown-it-imsize.js

**Comment by ToniWonKanobi** [comment]
I'm not a JavaScript guy, so I don't really know :(

We basically need to identify that any string of text following the [optional] image title `title` should be passed unaffected to the resultant `<img>` within the `<figure>`, right?

Not sure how to do that :/

**Comment by arve0** [comment]
Then maybe do a [regex plugin](https://jsfiddle.net/arve0/nz0Lb6ox/)? Or hire someone.

Closing, as this is outside the scope of markdown-it-implicit-figures.
